---
bibliography: "../references.bib"
link-citations: yes
csl: "../harvard-the-university-of-melbourne.csl"
# output: pdf_document
output: word_document
---

This thesis analysing population-level linked administrative data for Aboriginal and Torres Strait Islander children born in WA between 2000 and 2013 has a number of significant findings. Firstly that first placements in OOHC have been occurring at increasingly earlier ages, that when a child who has siblings is removed in the majority of cases their siblings are also removed at the same time, and that this increased risk of removal for siblings carries over to future children of their mother. Secondly, for the children who are ever-placed in OOHC, the prevalence of mental and neurodevelopmental health conditions was three times higher than children never-placed, with FASD and PTSD having the largest differences at around 10 and 7 times higher respectively, and FASD being more prevalent in children placed before the age of one and PTSD being more prevalent in children placed after the age of one. Thirdly, rates of PPHs were around twice as high for ever-placed children across all ages, with the highest rates occurring during the first few years of life for both ever- and never-placed children. Finally, placement in OOHC on average resulted in a reduction in PPHs, however rates of PPHs for ever-placed children never reached parity with that of never-placed children even after intervention by CPS.

<!-- #### *Relate to existing research* -->

<!-- Trends in siblings -->

The findings from this thesis have are consistent with and build on findings from previous studies. That child protection contacts were occurring at earlier ages for children born more recently mirrors findings from New South Wales [@zhou2010] and South Australia [@segal2019]. That children born to mothers living in metropolitan areas had higher rates of contact across all stages is also consistent with other findings from Western Australia [@odonnell2019;@lima2024]. The finding that children born to mothers with a prior removal were 16 times more likely to have been removed by age one is similar to the increased risk found in the few studies that examine this aspect [@jenkins2018;@odonnell2019]. Further, that 32% of children born to mothers with a prior child removal mirrors the experiences of mothers feeling 'written off' by CPS and that they feared having children removed at birth. Finally, the finding that in the majority of instances where a child with siblings is removed that their siblings are also removed on the same date is novel and highlights the importance that concurrent removals play in the over-representation of Aboriginal and Torres Strait Islander children in OOHC.

<!-- Health needs -->

That mental and neurodevelopmental health needs were overall three times higher for Aboriginal and Torres Strait Islander children with experience of OOHC adds an important finding to the literature. It provides a link between research showing that Aboriginal children generally have a higher burden of mental health needs than non-Indigenous children [@aihw2022b], and that children who have experience of OOHC go on to have increased mental and neurodevelopmental health needs as adults [@lima2019]. During the course of my PhD, @leckning2021 published a data linkage study to similar Chapter 4. They reported that Aboriginal and Torres Strait Islander children with experience of OOHC had higher rates of self-harm than Aboriginal and Torres Strait Islander children who did not have experience of OOHC, highlighting the elevated risk of poor mental health that those children who are placed in OOHC have, and the importance of providing them support to help address their mental health concerns.

<!-- PPH -->

While there has not been research published in Australia that specifically examines rates of PPHs for Aboriginal and Torres Strait Islander children depending on their experience of OOHC, there are a small number of articles that either examine admissions for all children depending on CPS involvement or for Aboriginal and Torres Strait Islander children but not considering CPS involvement. The research that only examines Indigenous status found the rate of admissions for PPHs for Aboriginal and Torres Strait Islander children in South Australia was 1.5 times higher compared to non-Indigenous children [@procter2020], and 1.7 times higher in New South Wales [@falster2016]. The only population-level study examining rates of hospitalisations according to level of CPS involvement found for all children in South Australia, not just Aboriginal and Torres Strait Islander children, rates of hospitalisations were 2.2 times higher for those with experience of OOHC [@gnanamanickam2020]. The finding in my research, that ever-placed Aboriginal and Torres Strait Islander children had a rate of PPH admissions 1.7 times higher and PPH bed days 2.3 times higher than never-placed Aboriginal and Torres Strait Islander children, should be considered in the context that these never-placed children already have higher rates of PPHs than non-Indigenous children. To put this in the same scale as reported by @falster2016 and @procter2020, who report rates of PPHs of 90.1 and 59.9 per 1,000 person-years respectively for Aboriginal and Torres Strait Islander children, ever-placed children had a rate of 144 admissions per 1,000 person years.

<!-- #### *Synthesising findings in terms of driving factors* -->

The individual chapters of my thesis contribute important findings to the literature on removals of Aboriginal and Torres Strait Islander children in WA and their health the context of OOHC. These findings highlight the need for greater support to prevent removals in the first instance, especially within sibling groups and for mothers with prior children removed, and to support carers to be able to meet the health needs of children in their care. To identify areas that could be targeted by policies and interventions to reduce rates of child removals and poorer health, we can look to the broader literature to understand the factors that lead to these outcomes. In contextualising my findings in the broader literature, there appear to be several antecedent factors common to the increased risk of removal for siblings of children removed, and the greater mental and neurodevelopmental health needs and elevated rates of PPHs for Aboriginal and Torres Strait Islander children in OOHC, which I explore here.

### Mental health {-}

My finding of the earlier age of removals of children over time, high rates of removals of children born to mothers who had a child previously removed, and that children with experience of OOHC had a higher prevalence of mental ill-health, highlights a cyclical relationship between mental health and child removals. The removal of children at any time, but in particular during their first weeks of life, is a traumatic experience for mothers. The consequence of this trauma can be long-term psychological damage and mental illness for the mother [@odonnell2015;@davis2019;@chamberlain2022]. Mental ill-health being considered a risk factor for child neglect means mothers that have previously had children removed may be at even greater risk of having subsequent children removed. Aboriginal and Torres Strait Islander children who experience maltreatment or OOHC have higher rates of self-harm during adolescence [@leckning2021] and mental health contacts once they reach adulthood [@lima2019], compared to Aboriginal and Torres Strait Islander children who have no CPS involvement. This therefore puts them at greater risk of having their own children removed, should they have any, continuing the seemingly unending, inter-generational cycle of poor mental health leading to increased risk of child removal.

### Substance use {-}

The use of alcohol and other substances during pregnancy can result in children being born with developmental disorders such as foetal alcohol spectrum disorder or neonatal withdrawal syndrome. For some mothers, substance use is a coping mechanism and is often comorbid with mental ill-health, both of which increase their likelihood of having contact with child protective services [@odonnell2015;@oleary2020;@tan2022]. If child removals are leading to or contributing to poor mental health and the continuation or uptake of substance use, then this may lead to repeated removal of children and increased prevalence of conditions like FASD, as seen in Chapter 4. That children with experience of OOHC had higher rates of intellectual disability, who may grow up to have children of their own, means they will be at greater risk of having their own children removed [@lima2022]. This dynamic highlights another cyclical relationship between child removals and neurodevelopmental conditions like intellectual disability.

### Housing {-}

Housing is relevant to both the rates of child removals and PPHs. Poor quality and overcrowded housing lead to increased rates of conditions like skin infections and respiratory conditions [@anderson2012], which were among the most common conditions identified in Chapter 5. Overcrowded and inadequate housing is classified as child neglect in the Department of Communities’ casework practice manual [@dcpneglect]. Overcrowding may be due to family members taking in other family members temporarily to support them through challenging circumstances [@ahv2020;@williams2020], an act that seems the opposite of neglect. Inadequate housing is also linked to issues, such as alcohol and substance use and difficulties with employment [@guthrie2020], factors which further put families at risk of having children removed. The many consequences of poor quality and overcrowded housing seems especially urgent to address when 19% of Indigenous Australians in WA were living in overcrowded housing in 2018-19 [@aihw2020f] and 33% of Indigenous households nationally having major structural problems [@aihw2020d].

### Poverty {-}

That nearly 50% of children were born to mothers living in the most disadvantaged socio-economic areas demonstrates that poverty affects many families of these children. The Department of Communities acknowledge that poverty is also a structural issue [@dcpneglect], which will likely compound many of the issues that families are experiencing which may lead to removal and therefore there is a need to address the structural causes of poverty. Not seeking timely healthcare for a child is treated as medical neglect, yet reasons why timely healthcare is not accessed may include cost or that primary care services are too far or transport is unavailable [@kalucy2019;@aihw2020f]. Homelessness and unstable housing, which can be both a cause and consequence of poverty, are risk factors for poor health and child protection involvement [@malvaso2022]. Child removal itself is a risk factor for worsening financial circumstances which will likely impact on the potential reunification of families. For parents who rely on financial welfare for their income, such as child welfare benefits [@bennett2020], their income typically reduces when their children are removed due to no longer entitled to child support payments. This adds another barrier to the parent's life, often making it even harder for them to seek reunification. 

### Racism {-}

Systemic racism must also be acknowledged. It negatively affects the health and wellbeing of Aboriginal and Torres Strait Islander people twice over, where the experience of racism directly impacts health [@kairuz2021;@thurber2021] and reduces the likelihood of seeking assistance from services where this racism is experienced [@langton2020] - both in healthcare and child and family support services. That child protection and healthcare services have embedded systemic racism is well documented [@davis2019;@guthrie2020;@harnett2020;@familymatters2021]. Caseworkers may assess traditional Aboriginal parenting practices as risky and therefore substantiate neglect, which compounds the increasing rates of removal for Aboriginal and Torres Strait Islander children [@harnett2020]. Systemic racism and the lack of culturally safe practices and processes is accepted as an issue that governments need to address, as evidenced by Priority Reform 3 of Closing the Gap [@ctg2020]. This is important as it makes clear that governments in Australia played a historic, contemporary, and fundamental role in intergenerational trauma due to Stolen Generations and the continued high rates of child protection involvement for Aboriginal and Torres Strait Islander families. Governments therefore have a responsibility to improve the way they work with and support Aboriginal and Torres Strait Islander families to keep from perpetuating harm.

## Implications

The point of highlighting these antecedent factors is that they are common causes of both child protection involvement and poor child health. To address these antecedent factors is to simultaneously reduce the risk of child removal and child ill-health, which is true for all families, regardless of whether children have already been removed. However, current health and social policy is failing to address these structural barriers faced by Aboriginal and Torres Strait Islander children and their families. If poor quality and overcrowded housing contributes to a decision of substantiated neglect and a reason for removing children, then repairing existing housing and building or purchasing new social and affordable housing that families at risk of child removal can live in, is likely to mitigate this risk. Increasing the supply of housing generally could also help families at risk of child removal who do not live in social housing, as increasing the housing stock could making it easier to find appropriate housing. Expanding the capacity, cultural safety and access to the primary healthcare system would ideally provide access to timely medical care and would contribute to reducing rates of poor health and reported medical neglect. Similarly, increasing the number and availability of culturally competent psychologists to assist parents in overcoming their mental health difficulties, often as a result of intergenerational trauma, would reduce the risk of removals due to the impact of mental ill-health. However, substantial systems change will require health and housing access to be addressed simultaneously [@gatwiri2021].

<!-- #### *Supporting existing families and children* -->

While preventing the first removal within a family should be a focus, families who have already had a child removed need to be provided greater support, both to increase the likelihood of successful reunification, as well as to prevent future removal of children. And yet these families, despite being a clearly identified population and well-known to child protective services, do not necessarily get the support they need to overcome the conditions that have led to their children being removed; especially when factors such as trauma or poverty may take years to overcome, by which time their children may be permanently in OOHC on until 18 orders [@turnbull2022]. Removing a child from their family so they are no longer deemed at risk of maltreatment should not be the final outcome of CPS involvement. If the goal is to reunite children with their families and prevent future removals, then support for the parent(s) needs to continue in order for the factors leading to the child removal to be addressed. Further, children who are not reunited with their families, currently the vast majority, need increased support as they leave OOHC as they become an adult, as there is a lack of funding and support for both the people exiting OOHC and the ACCOs that could provide the support [@gatwiri2021;@mendes2021].

<!-- #### *Critique of CPS* -->

Taking a step back from what can be changed within the child protection system or what additional supports they could offer, we should reflect on the current systemic issues which Aboriginal and Torres Strait Islander children are subject to in current child protection and health care services. The aforementioned cycle of children who were removed growing up and  having their own children removed was also identified by Grandmothers Against Removals, who stated “child removal has no role in Aboriginal child protection, because it can only create further trauma for both parent and child” [@turnbull2022]. Alternative methods of ensuring child safety are already being explored in Australia, with the Victorian Aboriginal Child Care Agency taking on the role of child protective services in conducting investigations and acting as the legal guardian for Aboriginal children in care, rather than the Victorian Government. Aboriginal Family Led Decision Making (AFLDM) is another a process by which power over decision making is shared with Aboriginal and Torres Strait Islander families and/or Elders [@snaiccafldm;@chamberlain2022]. This process, however, assumes child protective services have legitimate authority over the affairs of Aboriginal and Torres Strait Islander peoples, an assumption in tension with the principle of self-determination.

<!-- #### *Economics* -->

While the focus of the arguments to address child removals and ill-health should be addressed as a human rights issue, there is also an economic argument for addressing the factors that result in children entering out-of-home care, having increased health needs, and having hospitalisations for conditions that could have been treated in primary care settings. That the number of children entering out-of-home care is increasing over time and occurring at younger ages means the cost of keeping children in OOHC will only increase. Removing children within their first year of life means they will potentially be spending the next 18 years of their life in OOHC, and with the annual cost of keeping a child in OOHC in excess of $130,000 in the 2022-23 financial year in WA [@rogs2024], the total cost per child would be over \$2.3 million based on current costs. The AIHW has highlighted that the cost of OOHC is not just the operational costs, which were almost \$4 billion nationally in 2015-16 [@aihw2017welfare], but also the costs of negative family function and unresolved trauma from childhood maltreatment, estimated at \$5.4 billion and \$6.8 billion dollars respectively [@access2010;@kezelman2015]. Addressing the capacity and access issues of the public health system would help many families, not just those whose children are at risk of removal. Enabling all families to access timely healthcare and improving their housing conditions would help address the conditions that lead to child removals before they reach a critical point [@turnbull2022].

<!-- #### *Strengths* -->

Interventions must also focus on both eliminating risk factors and strengthening protective factors. Building and maintaining connections to  kin, community, and Country is important for the development of cultural connections and social and emotional wellbeing for Aboriginal and Torres Strait Islander people [@gee2014;@davis2019;@turnbull2022]. Developing and maintaining this identity and connection are protective factors for health and wellbeing, and disrupting this connection can lead to feelings of shame [@hreoc1997;@krakouer2023] and can have similar effects to experiencing disruptions in OOHC placements [@krakouer2018]. Strengthening communities so they can provide support in times of trauma and recovery from trauma can mitigate its impacts [@darwin2023], with strong family and community bonds helping to maintain and pass on connections to culture and Country to future generations [@kelly2009;@guthrie2020]. While maintaining this connection is embedded in the Aboriginal and Torres Strait Islander Child Placement Principle [@snaicc2019], the organisational adherence to this principle is mixed [@mcdowall2016;@jackomos2016]. Data from 2022 demonstrate that less than half of Aboriginal and Torres Strait Islander children in OOHC were with a caregiver who was themselves Aboriginal or Torres Strait Islander and only a third were with a relative or kin [@aihw2024], highlighting there is more work to be done in placing children according to the highest level of the Principle.

<!-- #### *Summary of implications* -->

With all this said, the policies, interventions, and other solutions must be informed by Aboriginal and Torres Strait Islander peoples in alignment with the principle of self-determination, a call which has been made many times [@norgard1976;@hreoc1997;@tilbury2009;@yoorrook2023]. Policies that address structural issues will need to be culturally safe, such as being considerate of local customs and activities like Sorry Business or consulting with Elders [@guthrie2020;@lonne2021], highlighting that ACCOs are well positioned to develop solutions that meet the needs of their local community [@williamson2016;@mendes2021]. Policies will also need to address distrust in government services [@guthrie2020], caused by activities like removing children from parents who had reached out to CPS for help caring for their children [@newton2020], removing children without discussing it with their parents [@newton2024], or removing children from mothers experiencing family and domestic violence who reach out for support [@meyer2022]. Finally, truth telling and accountability will be part of the pathway to healing, as called for in the Uluru Statement from the Heart [@ulurustatement]. If all of these aspects of Aboriginal-led policy design, system reform, reconciliation, and cultural safety are implemented, it may still take years to overcome decades of intergenerational disadvantage and trauma. Interventions to reduce the rate and number of Aboriginal and Torres Strait children in out-of-home care and improve their health, and the health of Aboriginal children generally, must plan for both immediate and intergenerational change. 

## Contemporary landscape

Since 2020, when the follow-up of the data ended, there have been important developments across states and territories and at the federal level, which I review here.

### Western Australia {-}

*Aboriginal Empowerment Strategy*

Given the many recommendations to provide greater funding to ACCOs and support them to design and implement strategies that are relevant for their local communities, the WA government’s *Aboriginal Empowerment Strategy* [@dpcwa2021] suggests a move in this direction. This policy covering 2021 to 2029 touches on many of the points made previously, with the policy document specifically referencing intergenerational trauma, cycles of disadvantage, supporting culture as a source of resilience, truth-telling and government accountability, and supporting ACCOs. The policy is aspirational and if fully implemented may have the potential to effect real change. The challenge for aspirational policies developed in the past is that their implementation has been limited in the ability to achieve improved outcomes [@aspf2016].

*Shifting child protection responsibility*

The WA government could implement the system currently used in Victoria, where the Victorian Aboriginal Child Care Agency is assigned the responsibility of conducting investigations and making decisions in cases of child maltreatment allegations when they relate to Aboriginal children. Additionally, granting legal guardianship status to an Aboriginal Community Controlled Organisation (ACCO), instead of the CEO of child protective services, has been suggested. While the delegation of legal authority to an ACCO is fundamentally still applying laws developed by a colonising power, it will hopefully result in a more culturally competent process, where the people completing investigations are not perceiving traditional Aboriginal and Torres Strait ways of parenting as maltreatment and support is easier to provide due to more trust in ACCOs than non-Aboriginal organisations in the child protection space. Currently the WA government is expanding funding for ACCOs in the OOHC sector [@accofunding], however there still remain a considerable number of non-Indigenous service providers, highlighting the need for greater ACCO involvement in the delivery of OOHC services to ensure cultural safety.

*Health navigator pilot*

The WA government is also trialling a health navigator program for children in care, in which health professionals are employed as ‘health navigators’ to help children, families, and carers navigate the healthcare system. A key component is that the program was the result of a co-design process and adopts a trauma-informed approach [@hnppslides], consistent with calls from advocacy groups [@turnbull2022]. As the pilot is currently being evaluated, the success of the program is not currently public knowledge. The design of the program seems promising and may have a real impact on supporting families and carers to access timely primary care, however health navigator programs implemented in other jurisdictions have had mixed success [@lenaghan2018;@kirby2021;@modderman2023].

*Aboriginal Family-Led Decision Making*

As mentioned previously, the WA government began a pilot of AFLDM in October 2021 [@afldm2021]. This was meant to be a two-year pilot, although the evaluation is yet to be made publicly available. However, the funding for this pilot was extended for two ACCOs, Wungening and Streeties, that were part of the original pilot [@afldmfunding], which could mean the programs have been effective, or that evaluation is ongoing. In terms of AFLDM outcomes, Wungening report that 81% of the safety plans they developed by collaborating with families were accepted by the Department of Communities [@wungening2023]. Wungening also offer an intensive family support services program, and 90% of the children referred to them by the Department of Communities for this program were not placed in OOHC. These figures suggest that ACCO-led child protection and family support services can be successful, which should encourage the WA government to support more ACCOs to provides these services across the state through their Aboriginal Empowerment Strategy, as Wungening only operate in the Boorloo (Perth) area and Binjareb Peel region.

### Interstate and federal {-}

*Safe and Supported Framework*

Safe and Supported: the National Framework for Protecting Australia’s Children 2021-2031 is a national framework which includes an "Aboriginal and Torres Strait Islander first action plan 2023-2026" which was developed in consultation with SNAICC [@safesupp]. There are many actions included in this policy targeted at improving child and family outcomes. This includes developing a set of co-designed guiding principles on how delegated authority, the transfer of legislative authority over aspects like child protective services to ACCOs, can be best implemented across the states and territories. An important component of this framework is that it includes both timeframes for completing its goals and a monitoring and evaluation framework that will determine whether the goals have been met - an important addition given the criticism in the Closing the Gap review that governments tend to write a lot of policy about 'what' they will do and relatively little on 'how' and 'why' [@ctgreview2024].

*Closing the Gap*

A recently published commissioned review of the Closing the Gap targets highlighted that little, if any, progress is being made toward implementing the Priority Reforms [@ctgreview2024]:

- Priority Reform 1 – Formal partnerships and shared decision-making.
- Priority Reform 2 – Building the community-controlled sector.
- Priority Reform 3 – Transforming government organisations.
- Priority Reform 4 – Shared access to data and information at a regional level.

The “lack of power sharing needed for joint decision-making, and the failure of governments to acknowledge and act on the reality that Aboriginal and Torres Strait Islander people know what is best for their communities” (page 3) was cited as the predominant reason for the stalling progress. The willingness to share power in decision making processes has similarly been cited as hampering the success of AFLDM pilots [@snaiccafldm;@atsicppvic]. While the Victorian Government has made some of these transformative changes, there has been poor progress overall which suggests there may be a long way to go before state and territory governments across Australia will be capable of meeting the aims set out in policies like *Safe and Supported* and the *Aboriginal Empowerment Strategy*.

*Voice, Treaty, and Truth*

The call for Voice, Treaty, and Truth remains, despite the failure of the recent referendum on a constitutional amendment for an Indigenous voice to parliament. While the failure of the referendum was a setback, progress toward Voice, Treaty, and Truth continues to be made at the state and territory level. South Australia recently passed the First Nations Voice Bill 2023 [@savoice], which created a First Nations Voice to Parliament in South Australia (SA Voice), the first Voice to Parliament in Australia. The SA Voice is formed of local and state-level members, elected by First Nations people in South Australia, with its priorities and operations decided by its members. In Victoria, a commitment to treaty was made in 2016, with the Victorian Government currently in negotiations with the First Peoples' Assembly of Victoria. At the same time, the Yoorrook Justice Commission is conducting a truth and justice inquiry, recently publishing a report on Victoria's child protection and criminal justice systems [@yoorrook2023]. The Queensland Government passed the Path to Treaty Act 2023 [@qldtreaty], providing a legislative framework to engage in truth telling and preparation for future treaty negotiations.

### Overview {-}

While WA has not committed to a treaty process yet, its state government should aspire to the progress made in other states. The Safe and Supported framework also suggest that the call for Voice, Treaty, and Truth, may eventually be achieved across Australia. This would hopefully position state, territory, and federal governments to be able to work in genuine partnership with Aboriginal and Torres Strait Islander communities to address the systemic and structural factors, created by colonisation, that have resulted in the over-representation of their children in OOHC and the inequitable burden of disease they face.

## Strengths and limitations

### Prioritising Aboriginal voices {-}

Throughout this research I prioritised the perspectives of Aboriginal people in guiding the direction that I have taken. I believe I have been successful in this, with the direction taken in chapters 3, 4, and 5, arising from findings from the I-CaRe WA study's qualitative research, discussions with the community reference group, and conversations with the I-CaRe WA study advisory group which included several Aboriginal investigators. There has been considerable learning on my behalf, in how to listen to what is being said and work out how it can be translated into a research question I can answer using administrative data. My intentions have been, as a non-Indigenous person and ally, to work in collaboration with my Aboriginal colleagues and provide analyses that meet the needs of their research agenda.

Part of the process of prioritising Aboriginal voices has also been to try and reflect on what I write and how I am writing it, as I provide interpretations of the findings that arose from my analyses. On reflection, I believe some of my writing could have been improved, changing the way that phrases are worded. For example, I often write "children having CPS contacts", which feels like it implies that the children are the ones making the contact with CPS, when in reality it is the Department of Communities that is the proactive agent in the administration CPS. In some instances I have reworded these kinds of phrases to shift focus back on CPS.

### Administrative data {-}

<!-- Data access, scale, topic -->

One of the greatest strengths of administrative data is the sheer scope and volume of data on important topics, that would otherwise be difficult and costly to gather information on. While service-level data is not collected for research purposes, with appropriate caution it can be used to gain insight into service delivery and aspects of health at a population level at relatively minimal cost.

For the data linkage specifically used for this research, federal data on the Medicare Benefits Schedule (MBS) and Pharmaceutical Benefits Scheme (PBS) were not linked. These are two important sources of information that, combined with hospital records and registries, would have painted a more complete picture of children’s health. For example, in Chapter 4 I estimate the prevalence of particular health conditions, however some of these conditions, such as attention deficit hyperactivity disorder, require a psychiatrist to diagnose and may be unlikely to appear in a diagnosis for a hospital visit and may not appear in the other registries. Having information on prescriptions of drugs used to treat certain conditions would improve the accuracy of these estimates.

Many of the linked datasets contain sensitive information that might otherwise be difficult to obtain through primary data collection methods. The child protection and family support data enables researchers to examine interactions with the child protection system, but only from the perspective of service use. For example, it can be used to examine the frequencies of contact with CPS, the ages at which they happen, the kinds of maltreatment and outcomes, rates of reunification. What these data cannot tell us is a family's experience of interacting with CPS, such as their experience of racism.

<!-- Design of system not for research, misses important topics -->

While official placement data for children within the Department of Communities is comprehensively captured for children who are removed from their families, informal care arrangements are not. Informal care arrangements are when a family member, often grandparents, take on caring responsibilities of their grandchildren who may otherwise have been removed by the Department of Communities. Informal care arrangements are not recorded in administrative data and are often the result of extended family wanting to keep children in their family and community, as well as meeting cultural obligations for the collective care of children. This lack of information means that there 'true' rate of children in OOHC is unknown, I was only able to examine rates for children in formal care arrangements.

The other main limitation of working with administrative data in data linkage contexts is the accuracy of the linkage and imputed variables like the Indigenous Status Flag. While data linkages often claim to be high quality and implement methods to ensure linkages are reliable [@eitelhuber2018], error rates such as incorrect links between records and unmade links between records that should have been made are not reported. This means the error is unable to be accounted for descriptively or within statistical models where this additional source of uncertainty would be important to incorporate. Further, as identified in Chapter 2, the Indigenous Status Flag is based on an algorithmic method of identifying Indigenous status within and across data collections. While it is an improvement over single-dataset identification, a comparison against the gold standard of self-identification has not been performed meaning the sensitivity and specificity of the algorithm cannot be truly assessed.

<!-- Relating findings back to the real world, inductive reasoning challenges -->

One of the other challenges of using observational data in general is trying to understand the reasons why particular patterns appear. One such example is the finding that potentially preventable hospitalisations for dental conditions increased following first placement in OOHC. There are a variety of reasons that could explain this trend, the problem is that inductively reasoning why trends appear is that it is difficult to know how accurate they are. These instances of trying to inductively explain findings that were not expected does provide useful direction for future topics of research, however, that may seek to replicate or further investigate these types of findings using different methodologies.

## Future directions

While my research has added important findings to the literature on the health of Aboriginal and Torres Strait Islander children in OOHC, there are several avenues of research which should be pursued given my findings.

### Disaggregation of geography {-}

The focus of this thesis has largely been on analysing the linked data without considering geographical location beyond remoteness areas. Producing population-level statistics for the entire state of WA, and more broadly nationally, is useful for policy makers, peak bodies, and advocacy groups. For individual ACCOs, analysis of the data disaggregated to a more localised context is also relevant. The WA Department of Communities divides Western Australia into individual child protection regions, which are discrete geographical areas serviced by a specific child protection office.

These child protection regions readily lend themselves to quantitative analysis, as demonstrated in their usage at the end of Chapter 3, since the areas they service are distinct and in theory only serviced by one office. While these regions may not neatly map to Aboriginal communities, they can be used to examine how service delivery or the prevalence of health conditions vary by region. Providing ACCOs, child protective services, and other service providers in these areas with analyses that are more localised and relevant will hopefully improve service design and planning. One example of this, would be to use these child protection regions to analyse PPH data, as in Chapter 5, where the results might give an indication as to the performance of healthcare systems in the respective regions.

### Systemic racism and neglect {-}

Neglect is typically the second most common form of maltreatment recorded for Aboriginal and Torres Strait Islander children in every state and territory, with rates of neglect being considerably higher than for non-Indigenous children. Neglect can take on many forms, for example in the WA child protection system neglect is defined as inadequate "food or shelter, medical treatment, supervision, care or nurturance to such an extent that their development is damaged or they are injured". That there are a wide variety of circumstances that could be perceived with neglect, combined with a caseworker conceiving that any one of these could lead to injury and the far higher rate of neglect for Aboriginal and Torres Strait Islander children, suggests that neglect could be one of the key ways in which systemic racism is expressed. Future research should, from an Aboriginal and/or Torres Strait Islander perspective, examine in detail the reasons being cited as neglect, to identify themes in reporting by non-Indigenous caseworkers that represent the misperception of traditional parenting practices as neglect. This kind of information could be used to develop cultural awareness training to help non-Indigenous caseworkers working with Aboriginal and Torres Strait Islander families and reduce rates of over-reporting.

### Scale of informal care arrangements {-}

Informal care arrangements, a form of OOHC that does not appear in child protection data, represents an important aspect of child protection statistics that has not been quantified. These care arrangements are typically with family members, often grandparents, and means that children who would have otherwise been formally removed by child protective services are placed in an environment that meets the Department of Communities' requirements that the child is no longer at risk of maltreatment, whilst also maintaining the child's connection to their family, community, and culture.

Measuring the scale of informal care arrangements will be important for several reasons. Firstly, reducing the rate of over-representation of Aboriginal and Torres Strait Islander children in OOHC is a goal for all states and territories under the Closing the Gap agreement. To truly measure this target requires measuring the numbers of children in informal care arrangements. If the numbers of children in informal care arrangements increase while the numbers in formal care arrangements decrease, progress toward reducing over-representation will appear to made when the underlying 'true' number of children in OOHC has not changed. For example, in Chapter 3 the increase in the rate of removals over time could be due to children transitioning from informal to formal care arrangements, however there is currently no way to assess this. Having a measure of the number of children in informal care arrangements will also be necessary for policies aiming to address precursory factors related to child ill health and formal care arrangements in OOHC, as only providing assistance to carers of children in formal care arrangements means extended family are, understandably, prioritising keeping children out of the child protection system but are not provided the same level of assistance.

One other reason why measuring the scale of informal care arrangements is important is it is part of the pathway into formal care arrangements. Measuring the trajectories that children take through the child protection system will be incomplete without data on when children are in informal care. Again, policies aiming to prevent children being removed should be supporting parents at risk of having a child removed and those caring for children in informal care arrangements. In terms of the Aboriginal and Torres Strait Islander Child Placement Principle, the extended family members who care for these children in informal care arrangements are also best positioned to maintain that child's connection to their family, community, culture, and Country.

### Timing of OOHC placement and condition onset {-}

As seen throughout my thesis age is related to both the timing of placements in OOHC, where the rate of placement is greater at younger ages, and the diagnosis of health conditions, whether due to aetiology, diagnostic guidelines, or other reasons. As highlighted in the discussion of Chapter 4, child maltreatment can lead to poor mental health as can the removal of children from their parents, community, and culture. While it would require a careful and considered analysis to manage the age-dependence seen in CPS involvement and onset of health conditions in a causal inference framework, future research could examine the impact of child maltreatment and CPS involvement on children's health.

### Expanding included datasets {-}

Data linkages can be costly and take a long time to be delivered, with the provision of data for the I-CaRe WA project taking approximately two years from first submission of the application to delivery of the dataset, although the onset of the COVID-19 pandemic was an exceptional factor. While expanding linkages to include multiple jurisdictions (i.e. other states or territories) and federal datasets adds even more time to the process, several of the limitations of the analyses performed throughout this thesis would be overcome by expanding the range of datasets, including cross-jurisdictional datasets such as health and child protection data and federal datasets such as the Medicare Benefits Schedule (MBS) and Pharmaceutical Benefits Scheme (PBS). The new PeopleWA system developed in Western Australia has expanded the range of datasets available and includes data across education, public housing, policing, and justice, in addition to the datasets used for this thesis.

The addition of MBS and PBS data would prove especially useful for obtaining more accurate estimates of the prevalence of health conditions. Medicare billing items and prescriptions for drugs used only in the treatment of specific conditions would provide data on healthcare in a primary care setting that is missing when using only hospital data and registries for select conditions. Similar to the work performed by @bourke2018 that demonstrated prevalence estimates of intellectual disability are improved when combining hospital and registry datasets, future work should examine how prevalence estimates of particular conditions are impacted by the datasets used. MBS and PBS data would also be useful in exploring what kinds of healthcare services were accessed prior to PPHs occurring. This would be useful to contextualise whether barriers to accessing healthcare were indeed present, as a lack of visits to primary care or dispensation of medication for known chronic conditions prior to a PPH occurring would be a better indicator than the PPH alone.

Cross-jurisdictional linkages would allow families to be followed up after they moved out of WA, meaning our analysis would have complete follow-up instead of right-censoring them on the incorrect date. It would also enable more complete identification of family relationships, where birth records were not provided for parents born outside of WA, and of health conditions and health service usage, as those who move out of WA would still be accessing healthcare.

## Summary

Initiatives to improve the health and wellbeing of Aboriginal children and reduce their over-representation in out-of-home care must be Aboriginal-led. Policy decisions made by government(s) must prioritise the voices of Aboriginal people and legitimately include them in decision making processes. To include Aboriginal voices in inquiries, hearings, and evaluations of programs, but not to implement their recommendations, will only result in maintaining the status quo of systems which are culturally unsafe and perpetuate colonial violence. Parents and carers know what their children's needs are, Aboriginal community-controlled organisations are best positioned to identify and address the needs of their communities. Policies need to be designed to be adaptable to local contexts - what works for Whadjuk Noongar people in the metropolitan Boorloo (Perth) area will not necessarily work for Yawuru people on their Country.